# Generated by Django 5.1.7 on 2025-03-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'PRODUCT'), (2, 'BLOG')], default=1),
        ),
    ]
