# Generated by Django 5.1.7 on 2025-03-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productreview_product_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
